{{ if .Values.enabled }}
{{- if .Values.isRBAC }}
apiVersion: {{ .Values.apiVersions.clusterRoleBinding }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "fluentd.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "fluentd.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "fluentd.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{ end }}