{{- if .Values.enabled -}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "obi.fullname" . }}
  labels:
    {{- include "obi.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.clusterRole.rules | nindent 2 }}
{{- end }}
{{- end }}

