{{- if .Values.enabled }}
{{- if or .Values.traces.token .Values.metrics.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obi.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "obi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.traces.token }}
  traces-headers: {{ printf "Authorization=Bearer %s" .Values.traces.token | quote }}
  {{- end }}
  {{- if .Values.metrics.token }}
  metrics-headers: {{ printf "Authorization=Bearer %s" .Values.metrics.token | quote }}
  {{- end }}
{{- end }}
{{- end }}

