apiVersion: v2
name: obi
version: 1.0.3
description: OpenTelemetry eBPF Instrumentation (OBI) for Kubernetes zero-code auto-instrumentation
type: application
home: https://logz.io/
maintainers:
  - name: Yotam Loewenbach
    email: yotam.loewenbach@logz.io
appVersion: main

