apiVersion: v2
name: logzio-k8s-events
description: A Helm chart for shipping Kubernetes deployments event information logs to Logz.io.
keywords:
  - logging
  - k8s
  - kubernetes
version: 1.0.0
appVersion: 0.0.4
maintainers:
  - name: Raul Gurshumov
    email: raul.gurshumo@logz.io