apiVersion: v2
name: logzio-fluentd
description: A Helm chart for shipping Kubernetes logs via Fluentd.
keywords:
  - logging
  - fluentd
version: 0.29.0
appVersion: 1.5.1
maintainers:
  - name: Miri Bar
    email: miri.ignatiev@logz.io
  - name: Tamir Michaeli
    email: tamir.michaeli@logz.io