apiVersion: v2
name: logzio-fluentd
description: A Helm chart for shipping Kubernetes logs via Fluentd.
keywords:
  - logging
  - fluentd
version: 0.30.0
appVersion: 1.5.1
maintainers:
  - name: Yotam loewenbach
    email: yotam.loewenbach@logz.io