{{- if .Values.trivyToLogzio.serviceAccount.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "trivy-to-logzio.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "trivy-to-logzio.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "trivy-to-logzio.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}