apiVersion: v2
name: prometheus-alerts-migrator
description: This Helm chart serves as a Kubernetes controller that automates the migration of Prometheus alert rules to Logz.io's alert format, facilitating monitoring and alert management in a Logz.io integrated environment.

type: application

version: 2.0.1

appVersion: "1.0.3"

maintainers:
- name: yotamloe
  email: yotam.loewenbach@logz.io