image: docker.elastic.co/beats/filebeat
imageTag: 7.8.1
nameOverride: ""
fullnameOverride: filebeat

winlogbeatImage: docker.io/logzio/logzio-winlogbeat
winlogbeatImageTag: 0.0.1

filebeatWindowsImage: docker.io/logzio/logzio-filebeat-win
filebeatWindowsImageTag: 0.0.1

apiVersions:
  configMap: v1
  daemonset: apps/v1
  clusterRoleBinding: rbac.authorization.k8s.io/v1
  clusterRole: rbac.authorization.k8s.io/v1
  serviceAccount: v1
  secret: v1

managedServiceAccount: true

clusterRoleRules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list

logzioCert:
  SectigoRSADomainValidationSecureServerCA.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIGEzCCA/ugAwIBAgIQfVtRJrR2uhHbdBYLvFMNpzANBgkqhkiG9w0BAQwFADCB
    iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
    cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
    BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTgx
    MTAyMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjCBjzELMAkGA1UEBhMCR0IxGzAZBgNV
    BAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UE
    ChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4g
    VmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEA1nMz1tc8INAA0hdFuNY+B6I/x0HuMjDJsGz99J/LEpgPLT+N
    TQEMgg8Xf2Iu6bhIefsWg06t1zIlk7cHv7lQP6lMw0Aq6Tn/2YHKHxYyQdqAJrkj
    eocgHuP/IJo8lURvh3UGkEC0MpMWCRAIIz7S3YcPb11RFGoKacVPAXJpz9OTTG0E
    oKMbgn6xmrntxZ7FN3ifmgg0+1YuWMQJDgZkW7w33PGfKGioVrCSo1yfu4iYCBsk
    Haswha6vsC6eep3BwEIc4gLw6uBK0u+QDrTBQBbwb4VCSmT3pDCg/r8uoydajotY
    uK3DGReEY+1vVv2Dy2A0xHS+5p3b4eTlygxfFQIDAQABo4IBbjCCAWowHwYDVR0j
    BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFI2MXsRUrYrhd+mb
    +ZsF4bgBjWHhMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAbBgNVHSAEFDASMAYGBFUdIAAw
    CAYGZ4EMAQIBMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0
    LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2Bggr
    BgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNv
    bS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDov
    L29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAMr9hvQ5Iw0/H
    ukdN+Jx4GQHcEx2Ab/zDcLRSmjEzmldS+zGea6TvVKqJjUAXaPgREHzSyrHxVYbH
    7rM2kYb2OVG/Rr8PoLq0935JxCo2F57kaDl6r5ROVm+yezu/Coa9zcV3HAO4OLGi
    H19+24rcRki2aArPsrW04jTkZ6k4Zgle0rj8nSg6F0AnwnJOKf0hPHzPE/uWLMUx
    RP0T7dWbqWlod3zu4f+k+TY4CFM5ooQ0nBnzvg6s1SQ36yOoeNDT5++SR2RiOSLv
    xvcRviKFxmZEJCaOEDKNyJOuB56DPi/Z+fVGjmO+wea03KbNIaiGCpXZLoUmGv38
    sbZXQm2V0TP2ORQGgkE49Y9Y3IBbpNV9lXj9p5v//cWoaasm56ekBYdbqbe4oyAL
    l6lFhd2zi+WJN44pDfwGF/Y4QA5C5BIG+3vzxhFoYt/jmPQT2BVPi7Fp2RBgvGQq
    6jG35LWjOhSbJuMLe/0CjraZwTiXWTb2qHSihrZe68Zk6s+go/lunrotEbaGmAhY
    LcmsJWTyXnW0OMGuf1pGg+pRyrbxmRE1a6Vqe8YAsOf4vmSyrcjC8azjUeqkk+B5
    yOGBQMkKW+ESPMFgKuOXwIlCypTPRpgSabuY0MLTDXJLR27lk8QyKGOHQ+SwMj4K
    00u/I5sUKUErmgQfky3xxzlIPK1aEn8=
    -----END CERTIFICATE-----

configType: standard
filebeatWindowsConfigType: standard
winlogbeatConfigType: standard

filebeatConfig:
  standardConfig:
    filebeat.yml: |-
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"

      processors:
        - add_cloud_metadata: ~
      fields:
        logzio_codec: ${LOGZIO_CODEC}
        token: ${LOGZIO_LOGS_SHIPPING_TOKEN}
        cluster: ${CLUSTER_NAME}
        type: ${LOGZIO_TYPE}
      fields_under_root: ${FIELDS_UNDER_ROOT}
      ignore_older: ${IGNORE_OLDER}
      output:
        logstash:
          hosts: ["${LOGZIO_LOGS_LISTENER_HOST}:5015"]
          ssl:
            certificate_authorities: ['/etc/pki/tls/certs/SectigoRSADomainValidationSecureServerCA.crt']
  autodiscoverConfig:
    filebeat.yml: |-
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            node: ${NODE_NAME}
            hints.enabled: true
            hints.default_config:
              type: container
              paths:
                - /var/log/containers/*-${data.kubernetes.container.id}.log
            include_annotations: '*'

      processors:
        - add_cloud_metadata: ~
      fields:
        logzio_codec: ${LOGZIO_CODEC}
        token: ${LOGZIO_LOGS_SHIPPING_TOKEN}
        cluster: ${CLUSTER_NAME}
        type: ${LOGZIO_TYPE}
      fields_under_root: ${FIELDS_UNDER_ROOT}
      ignore_older: ${IGNORE_OLDER}
      output:
        logstash:
          hosts: ["${LOGZIO_LOGS_LISTENER_HOST}:5015"]
          ssl:
            certificate_authorities: ['/etc/pki/tls/certs/SectigoRSADomainValidationSecureServerCA.crt']
  autoCustomConfig: {}

winlogbeatConfig:
  standardConfig:
    winlogbeat.yml: |-
      winlogbeat.event_logs:
        - name: Application
          ignore_older: 72h
        - name: Security
        - name: System

      fields:
        logzio_codec: ${LOGZIO_CODEC}
        token: ${LOGZIO_LOGS_SHIPPING_TOKEN}
        type: ${LOGZIO_TYPE}
      fields_under_root: ${FIELDS_UNDER_ROOT}

      processors:
        - rename:
            fields:
            - from: "agent"
              to: "winlogbeat_agent"
            ignore_missing: true
        - rename:
            fields:
            - from: "log.file.path"
              to: "source"
            ignore_missing: true
        - rename:
            fields:
            - from: "log"
              to: "log_information"
            ignore_missing: true

      output.logstash:
        hosts: ["${LOGZIO_LOGS_LISTENER_HOST}:5015"]
        ssl:
          certificate_authorities: ['C:\cert.crt']

filebeatWindowsConfig:
  standardConfig:
    filebeat.yml: |-
      filebeat.inputs:
      - type: container
        enabled: true
        paths:
          - c:\var\lib\docker\containers\*\*.log
        fields:
          logzio_codec: ${LOGZIO_CODEC}
          token: ${LOGZIO_LOGS_SHIPPING_TOKEN}
          type: ${LOGZIO_TYPE}
        symlinks: true
        fields_under_root: ${FIELDS_UNDER_ROOT}
        encoding: utf-8
        ignore_older: ${IGNORE_OLDER}
      filebeat.config.modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
      output.logstash:
        hosts: ["${LOGZIO_LOGS_LISTENER_HOST}:5015"]
        ssl.certificate_authorities: ["C:\\cert.crt"]
      processors:
      - rename:
          fields:
          - from: "agent"
            to: "filebeat_agent"
          ignore_missing: true
      - rename:
          fields:
          - from: "log.file.path"
            to: "source"
      - add_cloud_metadata: ~
      loggin.json: true
  autodiscoverConfig:
    filebeat.yml: |-
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            node: ${NODE_NAME}
            hints.enabled: true
            hints.default_config:
              type: container
              paths:
                - c:\var\lib\docker\containers\${data.kubernetes.container.id}\*.log
            include_annotations: '*'

      processors:
        - add_cloud_metadata: ~
      fields:
        logzio_codec: ${LOGZIO_CODEC}
        token: ${LOGZIO_LOGS_SHIPPING_TOKEN}
        cluster: ${CLUSTER_NAME}
        type: ${LOGZIO_TYPE}
      fields_under_root: ${FIELDS_UNDER_ROOT}
      ignore_older: ${IGNORE_OLDER}
      output:
        logstash:
          hosts: ["${LOGZIO_LOGS_LISTENER_HOST}:5015"]
          ssl:
            certificate_authorities: ['C:\\cert.crt']
  autoCustomConfig: {}

serviceAccount:
  create: true
  name: filebeat

terminationGracePeriod: 30
hostNetwork: true
windowsHostNetwork: false
dnsPolicy: ClusterFirstWithHostNet

daemonset:
  ignoreOlder: 3h
  logzioCodec: json
  logzioType: filebeat
  fieldsUnderRoot: true
  securityContext:
    runAsUser: 0
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  tolerations: {}
  volumes:
    - name: cert
      configMap:
        defaultMode: 0600
        name: logzio-logs-cert
    - name: config
      configMap:
        defaultMode: 0640
        name: filebeat-config
  volumeMounts:
    - name: config
      mountPath: /etc/filebeat.yml
      readOnly: true
      subPath: filebeat.yml
    - name: cert
      mountPath: /etc/pki/tls/certs/SectigoRSADomainValidationSecureServerCA.crt
      readOnly: true
      subPath: SectigoRSADomainValidationSecureServerCA.crt

winlogbeatDaemonset:
  ignoreOlder: 3h
  logzioCodec: json
  logzioType: winlogbeat
  fieldsUnderRoot: true
  securityContext:
    runAsUser: 0
  tolerations: {}
  volumes:
    - name: cert
      configMap:
        defaultMode: 0600
        name: logzio-logs-cert
    - name: config
      configMap:
        defaultMode: 0640
        name: winlogbeat-config
  volumeMounts:
    - name: config
      mountPath: C:\winlogbeat-7.15.2-windows-x86_64\etc
      readOnly: true

filebeatWindowsDaemonset:
  ignoreOlder: 3h
  logzioCodec: json
  logzioType: filebeat-win
  fieldsUnderRoot: true
  securityContext:
    runAsUser: 0
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  tolerations: {}
  volumes:
    - name: cert
      configMap:
        defaultMode: 0600
        name: logzio-logs-cert
    - name: config
      configMap:
        defaultMode: 0640
        name: filebeat-windows-config
  volumeMounts:
    - name: config
      mountPath: C:\filebeat-7.15.2-windows-x86_64\etc
      readOnly: true

secrets:
  logzioShippingToken: "fakeQAtOrFUZQRFMrvSqnKSEJhjjFZHz"
  logzioRegion: "us"
  clusterName: "chart-test"
